### ISSUE TITLE
auth.js Code in Node18 / SDK v3

### ISSUE THREAD

**Issue by NicoSchubbert** [aws-samples/aws-lambda-function-url-secured#7]
Hi, 
how the js code for the auth.js function would look like with the JS SDK V3? I tried to migrate it by my own, but I struggle with the signing and always get the error "The request signature we calculated does not match the signature you provided".

**Comment by jeromevdl** [comment]
Solved with https://github.com/aws-samples/aws-lambda-function-url-secured/commit/490183a8a752197c7dd521017bf4df41be5b8768
